apiVersion: v1
kind: Pod
metadata:
  name: memcached-operator-test
spec:
  restartPolicy: Never
  containers:
  - name: memcached-operator-test
    image: quay.io/coreos/operator-sdk-dev:memcached-operator-test
    imagePullPolicy: Always
    command: ["/go-test.sh"]
    resources:
      requests:
        cpu: 1
    env:
      - name: TEST_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace